const allTradersResult = {
    "statusCode": 200,
    "message":  [
         {
           "name": "test1",
           "gender": "test",
           "email": "email@mmo.com",
           "picture": "test",
           "password": "test",
           "phoneNumber": "test",
           "birthDate": "1989-12-31T22:00:00.000Z",
          "location": "test",
          "tradingStyle": "test",
          "yearsOfExperience": "test",
          "brokersUsed": "test",
          "isCommittedToEndScams": true
     },
       {
           "name": "test2",
           "gender": "test",
            "email": "email@mmo.com",
            "picture": "test",
           "password": "test",
            "phoneNumber": "test",
               "birthDate": "1989-12-31T22:00:00.000Z",
               "location": "test",
               "tradingStyle": "test",
               "yearsOfExperience": "test",
               "brokersUsed": "test",
               "isCommittedToEndScams": true
         }
     ,
       {
                   "name": "test3",
                   "gender": "test",
                   "email": "email@mmo.com",
                   "picture": "test",
                   "password": "test",
                   "phoneNumber": "test",
                   "birthDate": "1989-12-31T22:00:00.000Z",
                   "location": "test",
                   "tradingStyle": "test",
                   "yearsOfExperience": "test",
                   "brokersUsed": "test",
                   "isCommittedToEndScams": true
              }
        ,
        {
                       "name": "test4",
                       "gender": "test",
                       "email": "email@mmo.com",
                       "picture": "test",
                       "password": "test",
                       "phoneNumber": "test",
                       "birthDate": "1989-12-31T22:00:00.000Z",
                       "location": "test",
                       "tradingStyle": "test",
                       "yearsOfExperience": "test",
                      "brokersUsed": "test",
                      "isCommittedToEndScams": true
                 }
       ,
       {
        "name": "test5",
        "gender": "test",
        "email": "email@mmo.com",
        "picture": "test",
        "password": "test",
        "phoneNumber": "test",
        "birthDate": "1989-12-31T22:00:00.000Z",
       "location": "test",
       "tradingStyle": "test",
       "yearsOfExperience": "test",
       "brokersUsed": "test",
       "isCommittedToEndScams": true
  },
    {
        "name": "test6",
        "gender": "test",
         "email": "email@mmo.com",
         "picture": "test",
        "password": "test",
         "phoneNumber": "test",
            "birthDate": "1989-12-31T22:00:00.000Z",
            "location": "test",
            "tradingStyle": "test",
            "yearsOfExperience": "test",
            "brokersUsed": "test",
            "isCommittedToEndScams": true
      }
  ,
    {
                "name": "test7",
                "gender": "test",
                "email": "email@mmo.com",
                "picture": "test",
                "password": "test",
                "phoneNumber": "test",
                "birthDate": "1989-12-31T22:00:00.000Z",
                "location": "test",
                "tradingStyle": "test",
                "yearsOfExperience": "test",
                "brokersUsed": "test",
                "isCommittedToEndScams": true
           }
     ,
     {
                    "name": "test8",
                    "gender": "test",
                    "email": "email@mmo.com",
                    "picture": "test",
                    "password": "test",
                    "phoneNumber": "test",
                    "birthDate": "1989-12-31T22:00:00.000Z",
                    "location": "test",
                    "tradingStyle": "test",
                    "yearsOfExperience": "test",
                   "brokersUsed": "test",
                   "isCommittedToEndScams": true
              },
              {
                "name": "test9",
                "gender": "test",
                "email": "email@mmo.com",
                "picture": "test",
                "password": "test",
                "phoneNumber": "test",
                "birthDate": "1989-12-31T22:00:00.000Z",
               "location": "test",
               "tradingStyle": "test",
               "yearsOfExperience": "test",
               "brokersUsed": "test",
               "isCommittedToEndScams": true
          },
            {
                "name": "test10",
                "gender": "test",
                 "email": "email@mmo.com",
                 "picture": "test",
                "password": "test",
                 "phoneNumber": "test",
                    "birthDate": "1989-12-31T22:00:00.000Z",
                    "location": "test",
                    "tradingStyle": "test",
                    "yearsOfExperience": "test",
                    "brokersUsed": "test",
                    "isCommittedToEndScams": true
              }
          ,
            {
                        "name": "test11",
                        "gender": "test",
                        "email": "email@mmo.com",
                        "picture": "test",
                        "password": "test",
                        "phoneNumber": "test",
                        "birthDate": "1989-12-31T22:00:00.000Z",
                        "location": "test",
                        "tradingStyle": "test",
                        "yearsOfExperience": "test",
                        "brokersUsed": "test",
                        "isCommittedToEndScams": true
                   }
             ,
             {
                            "name": "test12",
                            "gender": "test",
                            "email": "email@mmo.com",
                            "picture": "test",
                            "password": "test",
                            "phoneNumber": "test",
                            "birthDate": "1989-12-31T22:00:00.000Z",
                            "location": "test",
                            "tradingStyle": "test",
                            "yearsOfExperience": "test",
                           "brokersUsed": "test",
                           "isCommittedToEndScams": true
                      },
                      {
                        "name": "test13",
                        "gender": "test",
                        "email": "email@mmo.com",
                        "picture": "test",
                        "password": "test",
                        "phoneNumber": "test",
                        "birthDate": "1989-12-31T22:00:00.000Z",
                       "location": "test",
                       "tradingStyle": "test",
                       "yearsOfExperience": "test",
                       "brokersUsed": "test",
                       "isCommittedToEndScams": true
                  },
                    {
                        "name": "test14",
                        "gender": "test",
                         "email": "email@mmo.com",
                         "picture": "test",
                        "password": "test",
                         "phoneNumber": "test",
                            "birthDate": "1989-12-31T22:00:00.000Z",
                            "location": "test",
                            "tradingStyle": "test",
                            "yearsOfExperience": "test",
                            "brokersUsed": "test",
                            "isCommittedToEndScams": true
                      }
                  ,
                    {
                                "name": "test15",
                                "gender": "test",
                                "email": "email@mmo.com",
                                "picture": "test",
                                "password": "test",
                                "phoneNumber": "test",
                                "birthDate": "1989-12-31T22:00:00.000Z",
                                "location": "test",
                                "tradingStyle": "test",
                                "yearsOfExperience": "test",
                                "brokersUsed": "test",
                                "isCommittedToEndScams": true
                           }
                     ,
                     {
                                    "name": "test16",
                                    "gender": "test",
                                    "email": "email@mmo.com",
                                    "picture": "test",
                                    "password": "test",
                                    "phoneNumber": "test",
                                    "birthDate": "1989-12-31T22:00:00.000Z",
                                    "location": "test",
                                    "tradingStyle": "test",
                                    "yearsOfExperience": "test",
                                   "brokersUsed": "test",
                                   "isCommittedToEndScams": true
                              },
                              {
                                "name": "test17",
                                "gender": "test",
                                "email": "email@mmo.com",
                                "picture": "test",
                                "password": "test",
                                "phoneNumber": "test",
                                "birthDate": "1989-12-31T22:00:00.000Z",
                               "location": "test",
                               "tradingStyle": "test",
                               "yearsOfExperience": "test",
                               "brokersUsed": "test",
                               "isCommittedToEndScams": true
                          },
                            {
                                "name": "test18",
                                "gender": "test",
                                 "email": "email@mmo.com",
                                 "picture": "test",
                                "password": "test",
                                 "phoneNumber": "test",
                                    "birthDate": "1989-12-31T22:00:00.000Z",
                                    "location": "test",
                                    "tradingStyle": "test",
                                    "yearsOfExperience": "test",
                                    "brokersUsed": "test",
                                    "isCommittedToEndScams": true
                              }
                          ,
                            {
                                        "name": "test19",
                                        "gender": "test",
                                        "email": "email@mmo.com",
                                        "picture": "test",
                                        "password": "test",
                                        "phoneNumber": "test",
                                        "birthDate": "1989-12-31T22:00:00.000Z",
                                        "location": "test",
                                        "tradingStyle": "test",
                                        "yearsOfExperience": "test",
                                        "brokersUsed": "test",
                                        "isCommittedToEndScams": true
                                   }
                             ,
                             {
                                            "name": "test20",
                                            "gender": "test",
                                            "email": "email@mmo.com",
                                            "picture": "test",
                                            "password": "test",
                                            "phoneNumber": "test",
                                            "birthDate": "1989-12-31T22:00:00.000Z",
                                            "location": "test",
                                            "tradingStyle": "test",
                                            "yearsOfExperience": "test",
                                           "brokersUsed": "test",
                                           "isCommittedToEndScams": true
                                      },
                                      {
                                        "name": "test21",
                                        "gender": "test",
                                        "email": "email@mmo.com",
                                        "picture": "test",
                                        "password": "test",
                                        "phoneNumber": "test",
                                        "birthDate": "1989-12-31T22:00:00.000Z",
                                       "location": "test",
                                       "tradingStyle": "test",
                                       "yearsOfExperience": "test",
                                       "brokersUsed": "test",
                                       "isCommittedToEndScams": true
                                  },
                                    {
                                        "name": "test22",
                                        "gender": "test",
                                         "email": "email@mmo.com",
                                         "picture": "test",
                                        "password": "test",
                                         "phoneNumber": "test",
                                            "birthDate": "1989-12-31T22:00:00.000Z",
                                            "location": "test",
                                            "tradingStyle": "test",
                                            "yearsOfExperience": "test",
                                            "brokersUsed": "test",
                                            "isCommittedToEndScams": true
                                      }
                                  ,
                                    {
                                                "name": "test23",
                                                "gender": "test",
                                                "email": "email@mmo.com",
                                                "picture": "test",
                                                "password": "test",
                                                "phoneNumber": "test",
                                                "birthDate": "1989-12-31T22:00:00.000Z",
                                                "location": "test",
                                                "tradingStyle": "test",
                                                "yearsOfExperience": "test",
                                                "brokersUsed": "test",
                                                "isCommittedToEndScams": true
                                           }
                                     ,
                                     {
                                                    "name": "test24",
                                                    "gender": "test",
                                                    "email": "email@mmo.com",
                                                    "picture": "test",
                                                    "password": "test",
                                                    "phoneNumber": "test",
                                                    "birthDate": "1989-12-31T22:00:00.000Z",
                                                    "location": "test",
                                                    "tradingStyle": "test",
                                                    "yearsOfExperience": "test",
                                                   "brokersUsed": "test",
                                                   "isCommittedToEndScams": true
                                              },
                                              {
                                                "name": "test25",
                                                "gender": "test",
                                                "email": "email@mmo.com",
                                                "picture": "test",
                                                "password": "test",
                                                "phoneNumber": "test",
                                                "birthDate": "1989-12-31T22:00:00.000Z",
                                               "location": "test",
                                               "tradingStyle": "test",
                                               "yearsOfExperience": "test",
                                               "brokersUsed": "test",
                                               "isCommittedToEndScams": true
                                          },
                                            {
                                                "name": "test26",
                                                "gender": "test",
                                                 "email": "email@mmo.com",
                                                 "picture": "test",
                                                "password": "test",
                                                 "phoneNumber": "test",
                                                    "birthDate": "1989-12-31T22:00:00.000Z",
                                                    "location": "test",
                                                    "tradingStyle": "test",
                                                    "yearsOfExperience": "test",
                                                    "brokersUsed": "test",
                                                    "isCommittedToEndScams": true
                                              }
                                          ,
                                            {
                                                        "name": "test27",
                                                        "gender": "test",
                                                        "email": "email@mmo.com",
                                                        "picture": "test",
                                                        "password": "test",
                                                        "phoneNumber": "test",
                                                        "birthDate": "1989-12-31T22:00:00.000Z",
                                                        "location": "test",
                                                        "tradingStyle": "test",
                                                        "yearsOfExperience": "test",
                                                        "brokersUsed": "test",
                                                        "isCommittedToEndScams": true
                                                   }
                                             ,
                                             {
                                                            "name": "test28",
                                                            "gender": "test",
                                                            "email": "email@mmo.com",
                                                            "picture": "test",
                                                            "password": "test",
                                                            "phoneNumber": "test",
                                                            "birthDate": "1989-12-31T22:00:00.000Z",
                                                            "location": "test",
                                                            "tradingStyle": "test",
                                                            "yearsOfExperience": "test",
                                                           "brokersUsed": "test",
                                                           "isCommittedToEndScams": true
                                                      }
            
        ]
}

export default allTradersResult; 